<a href="https://colab.research.google.com/github/Debayan2004/Andrew_Ng-Coursera/blob/main/Python_numpy_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.10903145 -0.44168631 -0.62638176  1.16115627  1.72488926]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.10903145 -0.44168631 -0.62638176  1.16115627  1.72488926]


Value of A and A transpose are same and hence error

In [6]:
print(np.dot(a,a.T))

4.922855612277885


In [8]:
a = np.random.randn(5,1)
print(a)

[[0.58601807]
 [0.62762031]
 [0.36097413]
 [1.08739377]
 [0.0367999 ]]


In [9]:
print(a.T)

[[0.58601807 0.62762031 0.36097413 1.08739377 0.0367999 ]]


In [10]:
print(np.dot(a,a.T))

[[0.34341717 0.36779684 0.21153736 0.6372324  0.02156541]
 [0.36779684 0.39390725 0.22655469 0.68247042 0.02309636]
 [0.21153736 0.22655469 0.13030232 0.39252102 0.01328381]
 [0.6372324  0.68247042 0.39252102 1.18242522 0.04001598]
 [0.02156541 0.02309636 0.01328381 0.04001598 0.00135423]]
